insert into packages (
  id,
  name,
  slug,
  description,
  best_for,
  price_from,
  price_to,
  vat_note,
  guest_min,
  guest_max,
  hours_included,
  sound_included,
  lighting_included,
  microphone_included,
  technical_coordination_included,
  backup_level,
  active,
  display_order,
  setup_included,
  setup_teardown_included
) values
  (
    'pkg_kompakt_firmafest',
    'Kompakt Firmafest',
    'kompakt-firmafest',
    'Et effektivt setup til mindre firmaevents, hvor I vil have styr på lyd, lys og en tryg afvikling uden unødigt overhead.',
    'Mindre firmafester og teams under cirka 70 gæster.',
    8900,
    10400,
    'Priser vises ekskl. moms. Transport og særlige tekniske behov beregnes tydeligt før bekræftelse.',
    20,
    70,
    4,
    true,
    true,
    false,
    false,
    'light',
    true,
    1,
    true,
    true
  ),
  (
    'pkg_dinner_party',
    'Dinner & Party',
    'dinner-party',
    'Den mest populære løsning til firmafester, julefrokoster og sommerfester, hvor middagen skal glide over i en stærk fest på dansegulvet.',
    'De fleste firmaevents mellem cirka 70 og 160 gæster.',
    13900,
    15900,
    'Priser vises ekskl. moms. Transport og særlige tekniske behov beregnes tydeligt før bekræftelse.',
    70,
    160,
    5,
    true,
    true,
    true,
    true,
    'standard',
    true,
    2,
    true,
    true
  ),
  (
    'pkg_stor_firmafest',
    'Stor Firmafest',
    'stor-firmafest',
    'Et mere omfattende setup med senior DJ, større lyd og ekstra koordinering til events, hvor det tekniske og logistiske skal sidde helt rigtigt.',
    'Større firmaevents og arrangementer fra cirka 160 til 350 gæster.',
    19900,
    23900,
    'Priser vises ekskl. moms. Transport og særlige tekniske behov beregnes tydeligt før bekræftelse.',
    160,
    350,
    6,
    true,
    true,
    true,
    true,
    'premium',
    true,
    3,
    true,
    true
  );

insert into djs (
  id,
  user_id,
  stage_name,
  public_display_name,
  legal_name,
  email,
  phone,
  city,
  regions,
  bio_short,
  bio_long,
  corporate_experience_years,
  languages,
  vibe_tags,
  specialties,
  sample_mix_url,
  photo_url,
  equipment_sound,
  equipment_lighting,
  can_handle_speeches,
  can_provide_mc,
  roster_layer,
  status,
  profile_quality_score,
  reliability_score,
  availability_freshness_score,
  last_availability_update,
  approved_for_shortlist,
  event_type_focuses
) values
  (
    'dj_mikkel',
    null,
    'DJ Mikkel',
    'DJ Mikkel',
    'Mikkel Andersen',
    'mikkel@djconnect.demo',
    '+45 20 11 22 33',
    'København',
    array['København / Sjælland'::region, 'Hele Danmark / andet'::region],
    'Sikker corporate DJ med styr på både middag, taler og dansegulv.',
    'Mikkel leverer rolige middagssetups, taler med tydelig mikrofon og et sikkert løft på dansegulvet, når gæsterne er klar.',
    11,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Elegant middag først, fest senere'::vibe_tag, 'Bred firmafest for alle aldre'::vibe_tag, 'High-energy dansegulv'::vibe_tag],
    array['stærk til middag-til-dansegulv overgang', 'erfaren med taler og præsentationer', 'klassiske firmafest-hits'],
    'https://example.com/mixes/dj-mikkel.mp3',
    'https://i.pravatar.cc/400?img=12',
    true,
    true,
    true,
    true,
    'core',
    'approved',
    96,
    95,
    96,
    now() - interval '4 days',
    true,
    array['Firmafest'::event_type, 'Middag og efterfest'::event_type, 'Julefrokost'::event_type, 'Kick-off'::event_type]
  ),
  (
    'dj_maja_k',
    null,
    'Maja K.',
    'Maja K.',
    'Maja Kristensen',
    'maja@djconnect.demo',
    '+45 21 44 55 66',
    'Aarhus',
    array['Aarhus / Østjylland'::region, 'Fyn'::region, 'Hele Danmark / andet'::region],
    'Elegant og moderne DJ med fokus på brede firmaevents og stærk musikalsk timing.',
    'Maja er stærk i events, hvor publikum spænder bredt, og hvor overgangene mellem middag, taler og fest skal føles helt naturlige.',
    9,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Bred firmafest for alle aldre'::vibe_tag, 'Moderne dance/pop'::vibe_tag, 'Internationalt publikum'::vibe_tag],
    array['bred appel på tværs af aldersgrupper', 'sikker energiopbygning', 'fleksibel til corporate brief'],
    'https://example.com/mixes/maja-k.mp3',
    'https://i.pravatar.cc/400?img=32',
    true,
    true,
    true,
    false,
    'core',
    'approved',
    94,
    92,
    88,
    now() - interval '9 days',
    true,
    array['Firmafest'::event_type, 'Sommerfest'::event_type, 'Reception'::event_type, 'Jubilæum'::event_type]
  ),
  (
    'dj_rasmus',
    null,
    'DJ Rasmus',
    'DJ Rasmus',
    'Rasmus Vinter',
    'rasmus@djconnect.demo',
    '+45 29 10 18 44',
    'Odense',
    array['Fyn'::region, 'København / Sjælland'::region, 'Sydjylland'::region],
    'Leverer trygge firmaevents med tydelig struktur og god energi hele aftenen.',
    'Rasmus er den type DJ, som får både kolleger, ledelse og festudvalg til at føle, at aftenen er under kontrol fra start til slut.',
    13,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Julefrokost med singalong og klassikere'::vibe_tag, 'Disco, funk og 80’er/90’er'::vibe_tag, 'High-energy dansegulv'::vibe_tag],
    array['julefrokoster med blandet publikum', 'klassiske cross-over hits', 'stærk crowd reading'],
    'https://example.com/mixes/rasmus.mp3',
    'https://i.pravatar.cc/400?img=47',
    true,
    true,
    true,
    true,
    'core',
    'approved',
    95,
    97,
    74,
    now() - interval '18 days',
    true,
    array['Julefrokost'::event_type, 'Firmafest'::event_type, 'Middag og efterfest'::event_type, 'Sommerfest'::event_type]
  ),
  (
    'dj_sofie',
    null,
    'DJ Sofie',
    'DJ Sofie',
    'Sofie Lund',
    'sofie@djconnect.demo',
    '+45 30 21 11 09',
    'København',
    array['København / Sjælland'::region, 'Hele Danmark / andet'::region],
    'Stilsikker DJ til corporate middage, receptioner og festlige overgange.',
    'Sofie arbejder med en varm, moderne og stilren tilgang, som passer godt til virksomheder, der vil have et professionelt udtryk uden at miste feststemningen.',
    8,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Elegant middag først, fest senere'::vibe_tag, 'Rolig lounge og baggrund'::vibe_tag, 'Moderne dance/pop'::vibe_tag],
    array['middagsmusik med elegance', 'sikker speeches-afvikling', 'gør dansegulvet klar uden at larme'],
    'https://example.com/mixes/sofie.mp3',
    'https://i.pravatar.cc/400?img=5',
    true,
    true,
    true,
    false,
    'extended',
    'approved',
    91,
    90,
    100,
    now() - interval '2 days',
    true,
    array['Middag og efterfest'::event_type, 'Reception'::event_type, 'Firmafest'::event_type, 'Jubilæum'::event_type]
  ),
  (
    'dj_anders',
    null,
    'DJ Anders',
    'DJ Anders',
    'Anders Kjeldsen',
    'anders@djconnect.demo',
    '+45 31 98 77 21',
    'Aalborg',
    array['Aalborg / Nordjylland'::region, 'Hele Danmark / andet'::region],
    'Erfaren til store firmaevents med fokus på driftssikkerhed og lyd.',
    'Anders er stærk i større set-ups, hvor lydtryk, koordinering og backup-planer er afgørende for en rolig afvikling.',
    15,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['High-energy dansegulv'::vibe_tag, 'Bred firmafest for alle aldre'::vibe_tag, 'Disco, funk og 80’er/90’er'::vibe_tag],
    array['store venues og komplekse setups', 'stærk lydteknisk koordinering', 'god backup-plan'],
    'https://example.com/mixes/anders.mp3',
    'https://i.pravatar.cc/400?img=15',
    true,
    true,
    true,
    true,
    'core',
    'approved',
    93,
    96,
    36,
    now() - interval '33 days',
    true,
    array['Firmafest'::event_type, 'Jubilæum'::event_type, 'Andet firmaarrangement'::event_type, 'Sommerfest'::event_type]
  ),
  (
    'dj_eva',
    null,
    'Eva H.',
    'Eva H.',
    'Eva Holm',
    'eva@djconnect.demo',
    '+45 32 14 66 90',
    'Vejle',
    array['Sydjylland'::region, 'Fyn'::region, 'Aarhus / Østjylland'::region],
    'Bredt musikalsk overblik og stærk til events med både middag og fest.',
    'Eva er et godt match til virksomheder, der ønsker en rolig og professionel DJ med mulighed for at skrue op, når tidspunktet er rigtigt.',
    10,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Bred firmafest for alle aldre'::vibe_tag, 'Elegant middag først, fest senere'::vibe_tag, 'Internationalt publikum'::vibe_tag],
    array['god til blandede gæstegrupper', 'balancerer taler og fest', 'tydelig kommunikation med venue'],
    'https://example.com/mixes/eva.mp3',
    'https://i.pravatar.cc/400?img=44',
    true,
    true,
    true,
    false,
    'extended',
    'approved',
    90,
    88,
    88,
    now() - interval '13 days',
    true,
    array['Sommerfest'::event_type, 'Firmafest'::event_type, 'Middag og efterfest'::event_type, 'Reception'::event_type]
  ),
  (
    'dj_simon',
    null,
    'DJ Simon',
    'DJ Simon',
    'Simon Hedegaard',
    'simon@djconnect.demo',
    '+45 22 89 65 43',
    'Roskilde',
    array['København / Sjælland'::region, 'Sydjylland'::region, 'Hele Danmark / andet'::region],
    'Stærk til moderne firmafester, hvor det hele skal være nemt og professionelt.',
    'Simon er stabil, venlig og god til at få gæster i gang uden at overtage hele rummet.',
    6,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Moderne dance/pop'::vibe_tag, 'High-energy dansegulv'::vibe_tag, 'Internationalt publikum'::vibe_tag],
    array['moderne pop og klubbet energi', 'let og effektiv afvikling', 'god til korte setups'],
    'https://example.com/mixes/simon.mp3',
    'https://i.pravatar.cc/400?img=21',
    true,
    true,
    false,
    false,
    'extended',
    'pending',
    84,
    82,
    96,
    now() - interval '6 days',
    false,
    array['Firmafest'::event_type, 'Sommerfest'::event_type, 'Kick-off'::event_type]
  ),
  (
    'dj_nadia',
    null,
    'Nadia M.',
    'Nadia M.',
    'Nadia Mahmoud',
    'nadia@djconnect.demo',
    '+45 23 77 10 88',
    'Odense',
    array['Fyn'::region, 'København / Sjælland'::region],
    'Kurateret selskabs-DJ med stærk sans for dinner-to-party-flow.',
    'Nadia arbejder særligt godt med arrangementer, hvor middagen skal være elegant og festen skal starte på det rigtige tidspunkt.',
    12,
    array['Dansk'::dj_language, 'Engelsk'::dj_language],
    array['Elegant middag først, fest senere'::vibe_tag, 'Julefrokost med singalong og klassikere'::vibe_tag, 'Rolig lounge og baggrund'::vibe_tag],
    array['sikker overgang fra tale til dans', 'god til julefrokoster', 'skarp på corporate tone'],
    'https://example.com/mixes/nadia.mp3',
    'https://i.pravatar.cc/400?img=28',
    true,
    true,
    true,
    true,
    'core',
    'approved',
    97,
    94,
    58,
    now() - interval '22 days',
    true,
    array['Middag og efterfest'::event_type, 'Julefrokost'::event_type, 'Firmafest'::event_type, 'Reception'::event_type]
  );

insert into reviews (
  id,
  booking_id,
  dj_id,
  event_type,
  reviewer_label,
  rating,
  quote,
  approved,
  created_at
) values
  ('rev_1', null, 'dj_mikkel', 'Firmafest', 'HR Manager, SaaS-virksomhed i København', 5, 'Alt var professionelt fra første dialog til sidste nummer.', true, now() - interval '12 days'),
  ('rev_2', null, 'dj_rasmus', 'Julefrokost', 'Office Manager, konsulenthus i Aarhus', 5, 'Trygt, velkoordineret og med god fornemmelse for gæsterne.', true, now() - interval '20 days'),
  ('rev_3', null, 'dj_maja_k', 'Sommerfest', 'Festudvalg, produktionsvirksomhed i Odense', 5, 'Meget god til at læse rummet og ramme en bred medarbejdergruppe.', true, now() - interval '35 days'),
  ('rev_4', null, 'dj_sofie', 'Middag og efterfest', 'Office Manager, finansvirksomhed i København', 4, 'Elegant setup og god kommunikation.', true, now() - interval '41 days'),
  ('rev_5', null, 'dj_anders', 'Firmafest', 'HR Manager, logistikvirksomhed i Aalborg', 5, 'Der var fuldstændig styr på teknikken.', true, now() - interval '60 days'),
  ('rev_6', null, 'dj_eva', 'Reception', 'Assistant, konsulenthus i Vejle', 4, 'Diskret og professionel under receptionen.', true, now() - interval '22 days'),
  ('rev_7', null, 'dj_nadia', 'Julefrokost', 'Festudvalg, detailvirksomhed i Roskilde', 5, 'Præcis den tryghed vi manglede.', true, now() - interval '18 days'),
  ('rev_8', null, 'dj_mikkel', 'Kick-off', 'Founder, tech-startup i København', 5, 'Det var nemt at koordinere, og musikniveauet passede perfekt.', true, now() - interval '14 days'),
  ('rev_9', null, 'dj_simon', 'Firmafest', 'Office Manager, rådgivningshus i Aarhus', 4, 'God energi og meget enkel proces.', true, now() - interval '9 days'),
  ('rev_10', null, 'dj_anders', 'Jubilæum', 'Event committee, produktionsvirksomhed i Sydjylland', 4, 'Solid afvikling og en god fornemmelse for tempoet.', true, now() - interval '28 days');
